### ISSUE TITLE
test_temporal_ps

### ISSUE THREAD

**Issue by pytesnim** [AOtools/aotools#46]
Hello,
I wanted to test temporal_ps and I got the result that is attached here.  I see that fit doesn't match with the noise psd. What might be reason for this discrepancy? Thanks very much!
![figure_1](https://user-images.githubusercontent.com/5729656/48305067-2a451d00-e535-11e8-98d8-9aec341d00b4.png)

**Comment by matthewtownson** [comment]
Hi,

Thanks for bringing this up, I haven't had a chance to look into the temporal code much yet, it is still experimental at the moment. I am currently going through the majority codebase and making sure that everything is working correctly and generating example plots, I will have a look at the temporal code next and let you know what I find.

**Comment by pytesnim** [comment]
Hello Matthew,
Could it be that noise has a flat spectrum and you are trying to fit turbulence spectrum with it? 
Thanks very much for your response.
