### ISSUE TITLE
Units of phasescreens put out by the aotools.turbulence.phasescreen.ft_sh_phase_screen function

### ISSUE THREAD

**Issue by phillips-r** [AOtools/aotools#73]
Greetings,

I'm poking around with aotools some and I am having a little trouble understanding what the units are on the phasescreens put out by the aotools.turbulence.phasescreen.ft_sh_phase_screen function. In some places in the documentation, it seems to refer to the units are radians but then in other places it seems to refer to the units as nanometers of wave front deviation per unit length. Can anyone clear this up?

**Comment by andrewpaulreeves** [comment]
Hi @phillips-r,

The units from the phase screen creation functions, including ` aotools.turbulence.phasescreen.ft_sh_phase_screen` are definitely in **radians**. We should certainly write this into the function docs! Can you point us to where its indictated that it may be in nano-metres?

Thanks!

Andrew

**Comment by phillips-r** [comment]
Andrew,

Thanks for getting back so quick! I'll hunt down where the docs are unclear and get back to you. Is there a per unit length assumed with the phase screens? As in "radians per meter" etc?

**Comment by phillips-r** [comment]
Andrew,

appologies for getting back so late. I was able to track down where I found that and it seems to be in a couple of the places like "optical_propagation.ipynb" in the AOtools_tests section where there is a figure after input 5 that implies the units are "wavefront deviation (nm)". 

Can you confirm for me what the unit length scale is on the phase screen measurements? They're in radians, but radians per unit what? meters? kilometers? Thanks again for this great tool!

**Comment by andrewpaulreeves** [comment]
Hi @phillips-r,

OK - Thanks for digging this out. We can have a look and make sure it clear where the units are radians and where its in metres. We'll keep this issue open until its sorted.

Radians in phase screens are always a little confusing. 

The phase screens are in "radians of a wavelength", so it depends on what wavelength you are considering. If you are assuming r0 is specified at 500nm (which is normally standard), then that implies that if you get a value of 2pi in the phase screen, there is 500nm of path difference at that point. If you wanted to convert your phase screen to nm then, you must multiply by `500 / (2 pi)`. However, when you're building an "electric field" from the phase screen, for instance to use in some optical propagation algorithm, then the phase needs to be in units of radians of wavelength.

Does this help?

Andrew
