### ISSUE TITLE
Units for r0 to cn2 atmospheric conversions

### ISSUE THREAD

**Issue by aaronjswank** [AOtools/aotools#77]
The functions:  def cn2_to_r0  and r0_to_cn2  indicate in the documentation that the units of r0 are in cm.  The equations implemented appear to return r0 in meters.

Equations are found in reference: Tyson, Robert K., and Benjamin West Frazier. “Field Guide to Adaptive Optics”, Second Edition, SPIE Press, 2012.  and Fried, David L. "Anisoplanatism in adaptive optics." JOSA 72.1 (1982): 52-61.

**Comment by matthewtownson** [comment]
Thanks for finding this discrepancy, I will update the docs to state the correct units - meters
