### ISSUE TITLE
Regarding atmos_conversions 

### ISSUE THREAD

**Issue by XimmiChangeXi** [AOtools/aotools#86]
Hi, I am Muzammil Ahmad, currently I am working on my thesis project, and looking forward to use the AOTOOLS to generate results. However, I was trying to learn about the packages and functions of AOTOOLS. I looked up into the atmos_conversions.cn2_to_r0, in which I fed the function value of cn2 and it gave me the value of r0 in meters. So far so good.  I wanted to cross check the calculation so I calculated manually, by the formula I have of Fried Parameter which is r0 = 0.184*((lamda^2)/(Cn2*L))^(3/5). The value I calculated on paper approximately matched with one that I calculated with the function. I peeked into the documentation and author uses an alternate formula. But thing concerns me the most is that in both formulae there is an extra parameter we have to put which is range like L. The defined function doesn't ask for any value of L. I am wondering from where do it gets the value of L ? is it predefined? To make myself more clear shouldn't the function be like (when called) 
r0 = aotools.turbulence.atmos_conversions(cn2 = 1, lamda = 1, L = 1) 
The numbers are arbitrary and in meters. Shouldn't we feed the value of L (range) in meters too? 
Looking forward to hear.

**Comment by matthewtownson** [comment]
That is an interesting question.

When we are doing these conversions we are assuming that the turbulence follows some Kolmogorov (or maybe Von Karman) statistics. This works if some atmospheric turbulence hasn't been physically propagated  (either no propagation or using geometrical propagation). However, you are right that things change as you do physical propagation, including effect like scintillation coming in. As a first approximation, I think that this does not matter. If you are in a regime where this does matter, then I think you are better off referring to metrics which work for arbitrary statistics (e.g. wave-front error in nm), as using Fried parameter assumes that the statistics of the turbulence follow Kolmogorov turbulence in the first place.

Hope that helps,
Matt

**Comment by XimmiChangeXi** [comment]
Glad to hear from you Sir, Obviously it made some things clear. I am still trying to get along with the AOTOOLS. 
Thanks for now. :-)
